### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by TheGodSkill** [pimoroni/st7735-python#28]
OS: Raspbian Jessie 2020-04-10
Running on an Banana Pi M2 Zero

Python 2.7.13

Traceback (most recent call last):
  File "gif.py", line 45, in <module>
    spi_speed_hz=4000000
  File "/home/pi/.local/lib/python2.7/site-packages/ST7735/init.py", line 146, in init
    self._spi = spidev.SpiDev(port, cs)
IOError: [Errno 2] No such file or directory

I used the gif.py in the example folder with the deployrainbows.gif

**Comment by TheGodSkill** [comment]
I used the command
"python gif.py deployrainbows.gif"

**Comment by Gadgetoid** [comment]
This usually means you have not enabled SPI, which you can do with the shorthand: `sudo raspi-config nonint do_spi 0`
